---
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: mlflow
  labels:
    app.kubernetes.io/managed-by: mlflow-seldon
    app.kubernetes.io/name: mlflow
spec:
  name: iris
  predictors:
    - componentSpecs:
        - spec:
            containers:
              - name: classifier
                livenessProbe:
                  initialDelaySeconds: 80
                  failureThreshold: 200
                  periodSeconds: 25
                  successThreshold: 1
                  httpGet:
                    path: /health/ping
                    port: http
                    scheme: HTTP
                readinessProbe:
                  initialDelaySeconds: 80
                  failureThreshold: 200
                  periodSeconds: 25
                  successThreshold: 1
                  httpGet:
                    path: /health/ping
                    port: http
                    scheme: HTTP

      graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: >-
          gs://hellomlops-mlflow/mlflow_artifacts/1/6887f98225b9419f9681d68e7cdd9335/artifacts/random-forest-model
        logger:
          url: >-
            http://broker-ingress.knative-eventing.svc.cluster.local/demo/default
          mode: all
        name: classifier
      name: default
      replicas: 1
