apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlflow-controller.fullname" . }}
  labels:
    {{- include "mlflow-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mlflow-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mlflow-controller.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mlflow-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
             {{- if .Values.gitops.gitPasswordSecretName }}
          env:
          - name: ML_SERVER
            value: {{ .Values.mlserver }}
             {{- if .Values.gitops.gitPasswordSecretName }}
          - name: GIT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.gitops.gitPasswordSecretName }}
                key: {{ .Values.gitops.gitPasswordSecretKey }}
                optional: false
            {{- end }}
          envFrom:
          - configMapRef:
              name: {{ include "mlflow-controller.fullname" . }}-mlflow-cm
          {{- if .Values.envFromSecret }}
          - secretRef:
              name: {{ .Values.envFromSecret }}
          {{- end }}
          {{- if .Values.gitops.enabled }}
          - configMapRef:
              name: {{ include "mlflow-controller.fullname" . }}-gitops-cm
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
