apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlflow-controller.fullname" . }}
  labels:
    {{- include "mlflow-controller.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mlflow-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mlflow-controller.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mlflow-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: MLFLOW_TRACKING_URI
            value: {{ .Values.mlflow.MLFLOW_TRACKING_URI }}
          - name: stage
            value: {{ .Values.mlflow.stage }}
          - name: namespace
            value: {{ .Values.mlflow.namespace }}
          - name: backend
            value: {{ .Values.mlflow.backend }}
          #   {{- if .Values.gitops.enabled }}
          # - name: GIT_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: {{ .Values.gitops.gitPasswordSecretName }}
          #       key: {{ .Values.gitops.gitPasswordSecretKey }}
          #       optional: false
          #   {{- end }}
          {{- if .Values.envFromSecret }}
          envFrom:
          - secretRef:
              name: {{ .Values.envFromSecret }}
          {{- end }}
          {{- if .Values.gitops.enabled }}
          # envFrom:
          - configMapRef:
              name: {{ include "mlflow-controller.fullname" . }}-gitops-cm
          {{- end }}
          # envFrom:
          # - configMapRef:
          #     name: {{ include "mlflow-controller.fullname" . }}-cm
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
