# Default values for mlflow-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# -- replica count
replicaCount: 1

image:
  # -- image repository  
  repository: hellomlops/mlflow-deployment-controller
  # -- image pull policy
  pullPolicy: Always
  # -- image tag
  tag: "mlflow-controller-0.1.6"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

mlflow:
  enabled: true
  # -- mlflow tracking uri
  MLFLOW_TRACKING_URI: http://mlflow-service:5000
  # -- Stage To be Tracked From Mlflow
  stage: Staging
  # -- Namespace model to be deployed
  namespace: staging
  # -- Object Storage Used by mlflow supported gcs , blob , s3 
  backend: "blob"

mlserver: seldon

gitops:
  # -- enable/disable gitops
  enabled: true
  # -- git repository
  repository: github.com/rocket9-code/model-deployments
  # -- deployment files folder location
  deploymentLocation: /
  # -- git username
  gitUser: raghulkrishna
  # -- git password secret name
  gitPasswordSecretName: ""
  # -- git password secret key
  gitPasswordSecretKey: ""
  # git branch to be tracked
  BRANCH: main

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # -- If not set and create is true, a name is generated using the fullname template
  name: ""
# -- pod annotations
podAnnotations: {}
# pod security context
podSecurityContext: {}
  # fsGroup: 2000
# -- additional ENV from secret
envFromSecret: ""
# -- security context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# -- cpu memory resource config
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


# -- node selector
nodeSelector: {}
# -- tolerations
tolerations: []
# -- affinity
affinity: {}
