name: Integration test gitops in KinD [minio]
on:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mlserver: [seldon,kserve]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: engineerd/setup-kind@v0.5.0
      with:
        skipClusterCreation: "true"
        version: v0.17.0
    
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.8.1
    

    - name: Create KinD Cluster
      run: kind create cluster --config tests/kind-cluster-1-24.yaml
    
    - name: Testing
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system
        echo "current-context:" $(kubectl config current-context)
        echo "environment-kubeconfig:" ${KUBECONFIG}
        kubectl get nodes
        kubectl wait --for=condition=Ready nodes --all --timeout=600s
        
    - name: Install Mlflow
      run: ./tests/install_mlflow.sh

    - name: PF Mlflow
      run: ./tests/pf_mlflow.sh
    - uses: actions/setup-python@v4
      with:
        python-version: '3.7' 

    - name: Log model Mlflow
      run: ./tests/log_mlflow_model.sh

    - name: Install Kserve
      run: ./tests/install_kserve.sh

    - name: Install Seldon Core
      run: ./tests/install_seldon_core.sh
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and Push image
      run: ./tests/docker_build_push.sh

    - name: Install deployment controller ${{matrix.mlserver}}
      run: ./tests/install_${{matrix.mlserver}}_deployment_controller.sh
      env:
        mlserver: ${{matrix.mlserver}}

    