name: Build & Apply manifests in KinD
on:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: engineerd/setup-kind@v0.5.0
      with:
        skipClusterCreation: "true"
    # - name: Testing
    #   run: |
    #     kubectl cluster-info
    #     kubectl get pods -n kube-system
    #     echo "current-context:" $(kubectl config current-context)
    #     echo "environment-kubeconfig:" ${KUBECONFIG}

    - name: Create KinD Cluster
      run: kind create cluster --config tests/kind-cluster-1-24.yaml

    - name: Install Istio
      run: ./tests/install_seldon_core.sh

    